services:
  postgres:
    image: postgres:15
    container_name: loansimulationdb
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: loansimulationdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "root", "-d", "loansimulationdb"]
      interval: 10s
      retries: 5
      timeout: 5s
      start_period: 30s

  java-app:
    build: .
    container_name: java-app
    restart: always
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/loansimulationdb
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    entrypoint: ["java", "-jar", "/app/app.jar"]
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data:
    driver: local
